### ISSUE TITLE
Elaborate on CorrectAssemblyPath part documentation

### ISSUE THREAD

**Issue by curunoir** [cbenard/Core.System.ServiceProcess#2]
Hello and thanks for this package.

I would like to use it to upgrade an existing .net framework project and installer towards .net core.

The installer has custom actions with forms and stuff like service creation and it uses InstallContext class to get msi properties.
When I use your package to get these classes back I can't use a publish output in custom action installer as InstallerClass, otherwise I'm getting this error 

`ERROR: Unable to build custom action named 'Éléments de publication from xxx (Active)', InstallerClass property is only valid for assemblies.`

As the CorrectAssemblyPath part of the documentation is not very clear to me I wonder if it is related and what ti do exactly if it is so I would appreciate some light. :)

Best regards

**Comment by cbenard** [comment]
I'm not sure without seeing your code. This was a short-term pre-requisite I needed and it's just a ported copy of Microsoft's code with the extra stuff I wrote for `CorrectAssemblyPath()` for .NET Core/5+.

You'll probably have to debug it yourself. Feel free to submit any PRs, but I won't be able to dedicate any time on this to debugging others code consuming it. If you find any errors in it though, please do submit a PR.
